### ISSUE TITLE
Meteor 3 support

### ISSUE THREAD

**Issue by jamauro** [bhunjadi/meteor-mongo-transactions#11]
Closing

**Comment by bhunjadi** [comment]
I was planning to add a support for Meteor 3.
I first have to figure out how to migrate my app to Meteor 3 first and then have a look into the package. I have rough idea how this could work without fibers, but nothing I have tried yet to be certain that it'll work as expected.

**Comment by jamauro** [comment]
Cool, I’ve been experimenting but I’m running into this issue even on Meteor 2: https://forums.meteor.com/t/mongo-transactions-insert-is-not-being-picked-up-by-publication/61206/1

Any ideas?

**Comment by bhunjadi** [comment]
From the thread, it looks like oplog is necessary, correct? Which meant you needed to switch from free to paid tier in Mongo Atlas?

**Comment by jamauro** [comment]
Yes, that’s correct
