### ISSUE TITLE
Support for promises

### ISSUE THREAD

**Issue by bhunjadi** [bhunjadi/meteor-mongo-transactions#3]
Right now, `runInTransaction` supports only synchronous code with fibers.

Initially, I thought that adding support for promises would be achievable with [async_hooks](https://nodejs.org/api/async_hooks.html) by using `AsyncLocalStorage`. However, it looks like that because of the fibers `executionAsyncId()` always returns 0 which means that `AsyncLocalStorage` is not working as expected.

Workaround is:
```
runInTransaction(() => Promise.await(fnReturningPromise));
```

**Comment by jthomaschewski** [comment]
The workaround looks promising: Does it actually work? Any gotchas?
Because the README suggests to use hacks like `Meteor._sleepForMs`  etc.

I can imagine that the combination of both fibers and promises might whats problematic.

**Comment by bhunjadi** [comment]
Handling promises mentioned here is not the same case as in Readme, though. Here you only have a function returning the promise, and you have to wrap it in `Promise.await`. You don't need `Meteor._sleepForMs` here.

In Readme, we have a promise in a callback of `.insert` method, which is more complicated since we cannot control it. You could use `_sleepForMs`, but you should also estimate how many secs you want to wait, depending on how much time will the callback take.
PR #4 works around that issue, so you won't have to use sleep anymore. I've tested it for more than two months now and it appears to be working well.

Just to note that this is a band-aid on top of a band-aid solution (fibers). However, if you do find any problems with the package, please report and I'll try to find a solution.

**Comment by jthomaschewski** [comment]
Thanks for the quick answer! I will try the PR.

Althought maybe my usecase is already possible: Is it possible to use promise based async code within a `runTransaction` callback?
e.g:
```js
function doSomething() {
  const promisesAndFibersMixed = async () => {
     Collection1.insert({ ... })
     await somethingElse()
     Collection2.insert({ ... })
   }
   runInTransaction(() => Promise.await(promisesAndFibersMixed()))
}
```
(mixing fiber and async/await... )

> Just to note that this is a band-aid on top of a band-aid solution (fibers)

Yes, sure. I just have a Meteor App which would benefit from safety provided by db transactions - and replacing the fibers-based MongoDB wrapper in a grown Meteor app would be painful :D

**Comment by bhunjadi** [comment]
Yes, your use case should work already without the PR.
